import React from "react";
import { DocsPageLayout } from "@/components/docs-page-layout";
import { readComponentSource } from "@/lib/source-code";
import { LiveCodeBlock } from "@/components/live-code-block";
import {
  LiquidChromePlayground,
  LiquidChromePersonalizePanel,
} from "@/components/docs/previews/liquid-chrome-playground";

const basicUsageCode = `import { LiquidChrome } from "@workspace/ui/components/liquid-chrome"

<LiquidChrome 
  baseColor={[0.10, 0.10, 0.10]}
  speed={1.0}
  amplitude={0.6}
  interactive={true}
/>`;

export async function LiquidChromeDocs() {
  const sourceCode =
    (await readComponentSource("liquid-chrome")) ||
    "// Unable to load source code";

  return (
    <DocsPageLayout
      title="Liquid Chrome"
      description="A premium fluid liquid metal shader background effect with interactive mouse distortion."
      fullWidthPreview={true}
      preview={<LiquidChromePlayground />}
      personalizeContent={<LiquidChromePersonalizePanel />}
      previewCode={"// The code is dynamically generated by the playground"}
      usageCode={<LiveCodeBlock defaultCode={basicUsageCode} />}
      installPackageName="liquid-chrome"
      installSourceCode={sourceCode}
      installSourceFilename="components/ui/liquid-chrome.tsx"
      props={[
        {
          name: "baseColor",
          type: "[number, number, number]",
          default: "[0.1, 0.1, 0.1]",
          description: "Base RGB color tint. Use values 0.0 - 1.0.",
        },
        {
          name: "speed",
          type: "number",
          default: "1.0",
          description: "Animation speed multiplier.",
        },
        {
          name: "amplitude",
          type: "number",
          default: "0.6",
          description: "Detail level and distortion of the fluid waves.",
        },
        {
          name: "interactive",
          type: "boolean",
          default: "true",
          description: "Enables mouse distortion if true.",
        },
        {
          name: "className",
          type: "string",
          description: "Additional CSS classes for styling.",
        },
      ]}
    />
  );
}
